engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      Controversial/Superglobals:
        enabled: false
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
