language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: WITH_COVERAGE=true
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - source .travis/travis.sh
  - xdebug-disable
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;

script:
  - mkdir -p build/logs
  - run-tests

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter; fi

