language: php

sudo: false

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: WITH_COVERAGE=true
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - source .travis/travis.sh
  - source .travis/test-reporter.sh
  - xdebug-disable
  - travis_retry composer self-update

install:
  - rm composer.lock
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;

script:
  - mkdir -p build/logs
  - run-tests

before_script:
  - codeclimate-before-build

after_success:
  - codeclimate-after-build

