---
title: Category Archive
use:
    - blog_categories
generator:
    - TaxonomyArchiveGenerator
    - PaginationGenerator
pagination:
    provider: blog_categories
    perPage: 3
---
<?php
/**
 * @var string $taxonomyName
 * @var string $title
 * @var \Tapestry\Entities\Pagination $pagination
 */
$this->layout('_templates\default', ['title' => $title . ' &mdash; Page ' . $pagination->currentPage . ' of ' . $pagination->totalPages]); ?>

<section>
    <header>
        <p class="h6 mt4 caps m0">Blog Categories</p>
        <h1 class="h1 regular m0"><?= ucfirst($taxonomyName) ?></h1>
        <div class="h6 mono pt1 red border-top">&nbsp;<div>
    </header>
</section>


<div class="border-bottom pb3">
    <ul>
        <?php
        /**
         * @var \Tapestry\Entities\ViewFile $item
         */
        foreach($pagination->getItems() as $item) { ?>
            <li><a href="<?= $item->getUrl() ?>"><?= ucfirst($item->getData('title')); ?></a></li>
        <?php } ?>
    </ul>
</div>

<div class="center">
    <?php $this->insert('_views/pagination', ['pagination' => $pagination, 'permalink' => $permalink]); ?>
</div>

