---
title: Category Archive
use:
    - blog_categories
generator:
    - TaxonomyArchiveGenerator
    - PaginationGenerator
pagination:
    provider: blog_categories
    perPage: 3
---
<?php $this->layout('_templates\default', ['title' => $title . ' &mdash; Page ' . $pagination->currentPage . ' of ' . $pagination->totalPages]); ?>

<h2><?= $taxonomyName ?></h2>

<ul>
    <?php
    /**
     * @var \Tapestry\Entities\ViewFile $item
     */
    foreach($pagination->getItems() as $item) { ?>
        <li><a href="<?= $item->getPermalink() ?>"><?= $item->getData('title'); ?></a></li>
    <?php } ?>
</ul>

<pre><?php var_dump($pagination->getItems()); ?></pre>

