<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= $title . ' &mdash; ' . $this->site['title']; ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site['description']); ?>">
    <meta title="author" content="<?= (isset($author) ? $author : $this->site['author']); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body class="text-center">
<h1>Tapestry Scaffold</h1>
<div>Congratulations you have successfully scaffolded your first tapestry site.</div>
</body>
</html>