<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site('description')); ?>">
    <meta title="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body class="text-center">

<header>
    <h1><?= $this->site('title') ?></h1>
</header>

<hr>

<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/blog">Archive</a></li>
    <li><a href="/blog/categories">Categories</a></li>
    <li><a href="/blog/tags">Tags</a></li>
</ul>

<hr>

<main>
    <?= $this->section('content') ?>
</main>
</body>
</html>