---
layout: default
title: Blog Archive
use:
    - blog
---

<section>
    <header>
        <p class="h6 mt4 caps m0">Blog</p>
        <h1 class="h1 regular m0">Archive</h1>
        <div class="h6 mono pt1 red border-top">&nbsp;<div>
    </header>


    <ul>
        <?php
        $year = 0;

        /**
         * @var \Tapestry\Entities\ViewFile[] $blog_items
         * @var \Tapestry\Entities\ViewFile $item
         */
        foreach($blog_items as $item) {

            $itemYear = $item->getData('date')->format('Y');

            if ($itemYear != $year){
                $year = $itemYear;
                ?>
                <li><strong><?= $year ?></strong></li>
                <?php
            }

            ?>
            <li><a href="<?= $item->getUrl() ?>"><?= $item->getData('title') ?></a></li>
            <?php
        }
        ?>
    </ul>
</section>

