<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title')); ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : $this->site('description')); ?>">
    <link type="text/css" rel="stylesheet" href="<?= $this->url('css/main.css') ?>" />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Mono" rel="stylesheet">
    <link type="image/x-icon" rel="icon" href="<?= $this->url('img/favicon.ico') ?>"/>
    <meta title="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry"/>
</head>
<body class="text-center">

<header>
    <div class="flex justify-end bg-black white clearfix">
        <div class="flex items-center max-width-4 col-11 p2 mx-auto">
            <h1 class="h5 m0 flex flex-column col-6 caps white"><?= $this->site('title') ?></h1>
            <nav class="flex flex-column col-6 right-align">
                <a href="<?= $this->url() ?>">Home</a>
            </nav>
        </div>
    </div>
</header>

<main class="max-width-4 mx-auto p3">
    <?= $this->section('content') ?>
</main>
</body>
</html>