---
layout: default
title: My Website
use:
    - blog
---

<h1>Tapestry Scaffold</h1>
<div>Congratulations you have successfully scaffolded your first tapestry site.</div>

<ul>
<?php
    /**
     * @var \Tapestry\Entities\ViewFile[] $blog_items
     * @var \Tapestry\Entities\ViewFile $item
     */
    foreach($blog_items as $item) {
?>
    <li><a href="<?= $item->getPermalink() ?>"><?= $item->getData('title') ?></a></li>
<?php
    }
?>
</ul>