---
layout: default
title: My Website
use:
    - blog
    - blog_categories
---

<p>Congratulations you have successfully scaffolded your first tapestry site.</p>

<ul>
    <?php foreach(array_keys($blog_categories_items) as $item){
        ?><li><a href="<?= '/blog/categories/' . $item ?>"><?= $item ?></a></li><?php
    }?>
</ul>

<ul>
<?php
    /**
     * @var \Tapestry\Entities\ViewFile[] $blog_items
     * @var \Tapestry\Entities\ViewFile $item
     */
    foreach($blog_items as $item) {
?>
    <li><a href="<?= $item->getPermalink() ?>"><?= $item->getData('title') ?></a></li>
<?php
    }
?>
</ul>