<?php
/**
 * @var \League\Plates\Extension\RenderContext\RenderContext $v
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= (isset($title) ? $title : '') ?></title>
    <meta title="description" content="<?= (isset($description) ? $description : ''); ?>">
    <meta title="author" content="<?= (isset($author) ? $author : ''); ?>>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body class="text-center">
<h1>Tapestry Scaffold</h1>
<?php $v->insert('_templates/sidebar'); ?>
<div>Congratulations you have successfully scaffolded your first tapestry site.</div>
</body>
</html>