---
generator:
    - CollectionItemGenerator
---
<?php

/**
 * @var stdClass $previous_next
 * @var string $title
 * @var string $content
 */

$this->layout('_templates\default', ['title' => $title]);
?>

<article>
    <header>
        <h1><?= $title ?></h1>
    </header>
    <div><?= $content ?></div>
</article>

<ul>
<?php if (! is_null($previous_next->previous)){ ?>
    <li><a href="<?= $previous_next->previous->getUrl() ?>">Previous</a></li>
<?php } ?>
    <li><a href="/">Home</a></li>
<?php if (! is_null($previous_next->next)){ ?>
    <li><a href="<?= $previous_next->next->getUrl() ?>">Next</a></li>
<?php } ?>
</ul>

<pre><?php var_dump($previous_next); ?></pre>
