---
generator:
    - CollectionItemGenerator
---
<?php

/**
 * @var stdClass $previous_next
 * @var string $title
 * @var string $content
 */

$this->layout('_templates\default', ['title' => $title]);
?>

<article>
    <header>
        <ul class="h6 mt4 caps m0 list-inline list-reset">
            <?php foreach($categories as $category) { ?>
                <li><a href="<?= $this->url('blog/categories/' . $category) ?>"><?= $category ?></a></li>
            <?php } ?>
        </ul>
        <h1 class="h1 regular m0"><?= $title ?></h1>
        <div class="h6 mono pt1 red border-top">
            <?= $date->format('l jS \of F Y') ?>
        <div>
    </header>
    <div class="border-bottom pb3"><?= $content ?></div>
    <footer class="center">
        <ul class="list-reset list-inline">
            <?php if (! is_null($previous_next->previous)){ ?>
                <li><a href="<?= $previous_next->previous->getUrl() ?>">Previous</a></li>
            <?php } ?>
            <li><a href="/">Home</a></li>
            <?php if (! is_null($previous_next->next)){ ?>
                <li><a href="<?= $previous_next->next->getUrl() ?>">Next</a></li>
            <?php } ?>
        </ul>
    </footer>
</article>
