<?php
/**
 * @var \Tapestry\Entities\Pagination $pagination
 * @var string $permalink
 */ ?>
<ul>
    <?php if($previous = $pagination->getPrevious()){ ?>
        <li><a href="<?= $previous->getUrl() ?>">&larr;</a></li>
    <?php } ?>

    <?php foreach($pagination->getPages() as $key => $page) { ?>
        <?php if ($page->getUrl() === url($permalink)){ ?>
            <li><?= $key + 1 ?></li>
        <?php } else { ?>
            <li><a href="<?= $page->getUrl() ?>"><?= $key + 1 ?></a></li>
        <?php } ?>
    <?php } ?>

    <?php if($next = $pagination->getNext()){ ?>
        <li><a href="<?= $next->getUrl() ?>">&rarr;</a></li>
    <?php } ?>
</ul>